version: '3.2'
services:
  main:
    image: tsmean/tsfiddle
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
      labels:
        - "traefik.frontend.rule=Host:tsfiddle.tsmean.com"
        - "traefik.port=5638"
        - "traefik.docker.network=traefik"
    ports:
      - "5638:5638"
    networks:
      - traefik

networks:
  traefik:
    external: true
